//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsShelf.R {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicsShelf.R.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comics Shelf.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BASE_CANCEL_COMMAND {
            get {
                return ResourceManager.GetString("BASE_CANCEL_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BASE_OK_COMMAND {
            get {
                return ResourceManager.GetString("BASE_OK_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait....
        /// </summary>
        internal static string BASE_WAIT_MESSAGE {
            get {
                return ResourceManager.GetString("BASE_WAIT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Readed.
        /// </summary>
        internal static string FILE_COMIC_ALREADY_READED_LABEL {
            get {
                return ResourceManager.GetString("FILE_COMIC_ALREADY_READED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FILE_OPEN_COMIC_LABEL {
            get {
                return ResourceManager.GetString("FILE_OPEN_COMIC_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Comics.
        /// </summary>
        internal static string HOME_FEATURED_PAGE_TITLE {
            get {
                return ResourceManager.GetString("HOME_FEATURED_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Comics.
        /// </summary>
        internal static string HOME_FOLDERS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("HOME_FOLDERS_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string HOME_LIBRARY_MENU {
            get {
                return ResourceManager.GetString("HOME_LIBRARY_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put some CBZ files on your device and restart the app or set a different folder for your library..
        /// </summary>
        internal static string HOME_NO_COMIC_FILE_FOUND_ON_DEVICE_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("HOME_NO_COMIC_FILE_FOUND_ON_DEVICE_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comic file was found on device.
        /// </summary>
        internal static string HOME_NO_COMIC_FILE_FOUND_ON_DEVICE_TITLE {
            get {
                return ResourceManager.GetString("HOME_NO_COMIC_FILE_FOUND_ON_DEVICE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Reading.
        /// </summary>
        internal static string HOME_READING_FILES_SECTION_TITLE {
            get {
                return ResourceManager.GetString("HOME_READING_FILES_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added Comics.
        /// </summary>
        internal static string HOME_RECENT_FILES_SECTION_TITLE {
            get {
                return ResourceManager.GetString("HOME_RECENT_FILES_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Rated Comics.
        /// </summary>
        internal static string HOME_TOP_RATED_SECTION_TITLE {
            get {
                return ResourceManager.GetString("HOME_TOP_RATED_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Books Library.
        /// </summary>
        internal static string LIBRARY_MAIN_LABEL {
            get {
                return ResourceManager.GetString("LIBRARY_MAIN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string LIBRARY_MAIN_TITLE {
            get {
                return ResourceManager.GetString("LIBRARY_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to select the folder for the library.
        /// </summary>
        internal static string LIBRARY_SELECT_FOLDER_COMMAND {
            get {
                return ResourceManager.GetString("LIBRARY_SELECT_FOLDER_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may legally and freely download some public domain comics on the the following site.
        /// </summary>
        internal static string LIBRARY_SUGGESTION_MESSAGE {
            get {
                return ResourceManager.GetString("LIBRARY_SUGGESTION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As this is your first time here, you have NO LIBRARY defined yet. Click the button bellow and SELECT A FOLDER on your device that contains your comic book files (those files with the CBZ extension)..
        /// </summary>
        internal static string LIBRARY_UNDEFINED_FOLDER_MESSAGE {
            get {
                return ResourceManager.GetString("LIBRARY_UNDEFINED_FOLDER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading current database data.
        /// </summary>
        internal static string SEARCH_ENGINE_LOADING_DATABASE_DATA_MESSAGE {
            get {
                return ResourceManager.GetString("SEARCH_ENGINE_LOADING_DATABASE_DATA_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing the files structure.
        /// </summary>
        internal static string SEARCH_ENGINE_PREPARING_FILES_STRUCTURE_MESSAGE {
            get {
                return ResourceManager.GetString("SEARCH_ENGINE_PREPARING_FILES_STRUCTURE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing the folders structure.
        /// </summary>
        internal static string SEARCH_ENGINE_PREPARING_FOLDERS_STRUCTURE_MESSAGE {
            get {
                return ResourceManager.GetString("SEARCH_ENGINE_PREPARING_FOLDERS_STRUCTURE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for new comic files on the device.
        /// </summary>
        internal static string SEARCH_ENGINE_SEARCHING_COMIC_FILES_MESSAGE {
            get {
                return ResourceManager.GetString("SEARCH_ENGINE_SEARCHING_COMIC_FILES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking permissions.
        /// </summary>
        internal static string STARTUP_ENGINE_CHECK_PERMISSIONS_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_CHECK_PERMISSIONS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Data from Comic Files.
        /// </summary>
        internal static string STARTUP_ENGINE_EXTRACTING_COMICS_DATA_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_EXTRACTING_COMICS_DATA_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading database.
        /// </summary>
        internal static string STARTUP_ENGINE_LOADING_DATABASE_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_LOADING_DATABASE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings.
        /// </summary>
        internal static string STARTUP_ENGINE_LOADING_SETTINGS_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_LOADING_SETTINGS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating the library location.
        /// </summary>
        internal static string STARTUP_ENGINE_VALIDATING_LIBRARY_PATH_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_VALIDATING_LIBRARY_PATH_MESSAGE", resourceCulture);
            }
        }
    }
}
