//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsShelf.R {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicsShelf.R.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comics Shelf.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BASE_CANCEL_COMMAND {
            get {
                return ResourceManager.GetString("BASE_CANCEL_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BASE_OK_COMMAND {
            get {
                return ResourceManager.GetString("BASE_OK_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page {0} of {1}.
        /// </summary>
        public static string FILE_PAGESTATS_TEXT {
            get {
                return ResourceManager.GetString("FILE_PAGESTATS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FOLDER_DIALOG_CANCEL_COMMAND {
            get {
                return ResourceManager.GetString("FOLDER_DIALOG_CANCEL_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string FOLDER_DIALOG_CONFIRM_COMMAND {
            get {
                return ResourceManager.GetString("FOLDER_DIALOG_CONFIRM_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected folder:.
        /// </summary>
        public static string FOLDER_DIALOG_SELECTED_PATH_LABEL {
            get {
                return ResourceManager.GetString("FOLDER_DIALOG_SELECTED_PATH_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Selector.
        /// </summary>
        public static string FOLDER_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("FOLDER_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string HOME_FEATURED_PAGE_TITLE {
            get {
                return ResourceManager.GetString("HOME_FEATURED_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Comics.
        /// </summary>
        public static string HOME_FOLDERS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("HOME_FOLDERS_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the upper right button to define libraries containing some CBZ files..
        /// </summary>
        public static string HOME_LIBRARY_EMPTY_MESSAGE_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("HOME_LIBRARY_EMPTY_MESSAGE_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string HOME_LIBRARY_MENU {
            get {
                return ResourceManager.GetString("HOME_LIBRARY_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Reading.
        /// </summary>
        public static string HOME_READING_FILES_SECTION_TITLE {
            get {
                return ResourceManager.GetString("HOME_READING_FILES_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added Comics.
        /// </summary>
        public static string HOME_RECENT_FILES_SECTION_TITLE {
            get {
                return ResourceManager.GetString("HOME_RECENT_FILES_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Rated Comics.
        /// </summary>
        public static string HOME_TOP_RATED_SECTION_TITLE {
            get {
                return ResourceManager.GetString("HOME_TOP_RATED_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the buttons bellow to add a LOCAL or ONEDRIVE folder that contains your comic book files (those files with the CBZ extension)..
        /// </summary>
        public static string LIBRARY_EMPTY_MESSAGE_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("LIBRARY_EMPTY_MESSAGE_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have a library defined yet..
        /// </summary>
        public static string LIBRARY_EMPTY_MESSAGE_TITLE {
            get {
                return ResourceManager.GetString("LIBRARY_EMPTY_MESSAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder has no CBZ files. Choose a valid folder containing some comic book files on it..
        /// </summary>
        public static string LIBRARY_INVALID_FOLDER_MESSAGE {
            get {
                return ResourceManager.GetString("LIBRARY_INVALID_FOLDER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic Books Library.
        /// </summary>
        public static string LIBRARY_MAIN_LABEL {
            get {
                return ResourceManager.GetString("LIBRARY_MAIN_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string LIBRARY_MAIN_TITLE {
            get {
                return ResourceManager.GetString("LIBRARY_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Folder.
        /// </summary>
        public static string LIBRARY_NEW_LOCAL_FOLDER_COMMAND {
            get {
                return ResourceManager.GetString("LIBRARY_NEW_LOCAL_FOLDER_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive Folder.
        /// </summary>
        public static string LIBRARY_NEW_ONEDRIVE_FOLDER_COMMAND {
            get {
                return ResourceManager.GetString("LIBRARY_NEW_ONEDRIVE_FOLDER_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string LIBRARY_REMOVE_LIBRARY_COMMAND {
            get {
                return ResourceManager.GetString("LIBRARY_REMOVE_LIBRARY_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading current database data.
        /// </summary>
        public static string SEARCH_ENGINE_LOADING_DATABASE_DATA_MESSAGE {
            get {
                return ResourceManager.GetString("SEARCH_ENGINE_LOADING_DATABASE_DATA_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizing shelves structure.
        /// </summary>
        public static string SEARCH_ENGINE_ORGANIZING_SHELVES_STRUCTURES_MESSAGE {
            get {
                return ResourceManager.GetString("SEARCH_ENGINE_ORGANIZING_SHELVES_STRUCTURES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for comic files on your libraries.
        /// </summary>
        public static string SEARCH_ENGINE_SEARCHING_COMIC_FILES_MESSAGE {
            get {
                return ResourceManager.GetString("SEARCH_ENGINE_SEARCHING_COMIC_FILES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all Folder as Readed.
        /// </summary>
        public static string SPLASH_FILE_MARK_ALL_AS_READED_LABEL {
            get {
                return ResourceManager.GetString("SPLASH_FILE_MARK_ALL_AS_READED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Readed.
        /// </summary>
        public static string SPLASH_FILE_MARK_AS_READED_LABEL {
            get {
                return ResourceManager.GetString("SPLASH_FILE_MARK_AS_READED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Comic File.
        /// </summary>
        public static string SPLASH_FILE_OPEN_COMIC_LABEL {
            get {
                return ResourceManager.GetString("SPLASH_FILE_OPEN_COMIC_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading covers for Featured comic files.
        /// </summary>
        public static string STARTUP_ENGINE_EXTRACTING_DATA_FEATURED_FILES_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_EXTRACTING_DATA_FEATURED_FILES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading covers for Folders comic files.
        /// </summary>
        public static string STARTUP_ENGINE_EXTRACTING_DATA_FOLDERS_FILES_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_EXTRACTING_DATA_FOLDERS_FILES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading covers for all Remaining comic files.
        /// </summary>
        public static string STARTUP_ENGINE_EXTRACTING_DATA_REMAINING_FILES_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_EXTRACTING_DATA_REMAINING_FILES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading database.
        /// </summary>
        public static string STARTUP_ENGINE_LOADING_DATABASE_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_LOADING_DATABASE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings.
        /// </summary>
        public static string STARTUP_ENGINE_LOADING_SETTINGS_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_LOADING_SETTINGS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating the library location.
        /// </summary>
        public static string STARTUP_ENGINE_VALIDATING_LIBRARY_PATH_MESSAGE {
            get {
                return ResourceManager.GetString("STARTUP_ENGINE_VALIDATING_LIBRARY_PATH_MESSAGE", resourceCulture);
            }
        }
    }
}
