//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsShelf.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicsShelf.Settings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a new Local Drive library.
        /// </summary>
        internal static string ADD_LOCAL_DRIVE_LIBRARY_COMMAND {
            get {
                return ResourceManager.GetString("ADD_LOCAL_DRIVE_LIBRARY_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a new One Drive library.
        /// </summary>
        internal static string ADD_ONE_DRIVE_LIBRARY_COMMAND {
            get {
                return ResourceManager.GetString("ADD_ONE_DRIVE_LIBRARY_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to clear your local cache.
        /// </summary>
        internal static string LOCAL_CACHE_CLEAR_COMMAND {
            get {
                return ResourceManager.GetString("LOCAL_CACHE_CLEAR_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear your local cache ?.
        /// </summary>
        internal static string LOCAL_CACHE_CLEAR_CONFIRMATION {
            get {
                return ResourceManager.GetString("LOCAL_CACHE_CLEAR_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL CACHE.
        /// </summary>
        internal static string LOCAL_CACHE_TITLE {
            get {
                return ResourceManager.GetString("LOCAL_CACHE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megas.
        /// </summary>
        internal static string LOCAL_CACHE_UNITS {
            get {
                return ResourceManager.GetString("LOCAL_CACHE_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL DRIVE LIBRARIES.
        /// </summary>
        internal static string LOCAL_DRIVE_LIBRARIES_TITLE {
            get {
                return ResourceManager.GetString("LOCAL_DRIVE_LIBRARIES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE DRIVE LIBRARIES.
        /// </summary>
        internal static string ONE_DRIVE_LIBRARIES_TITLE {
            get {
                return ResourceManager.GetString("ONE_DRIVE_LIBRARIES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove the {0} library.
        /// </summary>
        internal static string REMOVE_LIBRARY_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("REMOVE_LIBRARY_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
