//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsShelf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicsShelf.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string COMMON_CANCEL_COMMAND {
            get {
                return ResourceManager.GetString("COMMON_CANCEL_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string COMMON_CONFIRM_COMMAND {
            get {
                return ResourceManager.GetString("COMMON_CONFIRM_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string COMMON_OK_COMMAND {
            get {
                return ResourceManager.GetString("COMMON_OK_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Path.
        /// </summary>
        public static string DRIVE_FOLDER_DIALOG_SELECTED_PATH_LABEL {
            get {
                return ResourceManager.GetString("DRIVE_FOLDER_DIALOG_SELECTED_PATH_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory for your comics library.
        /// </summary>
        public static string DRIVE_FOLDER_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("DRIVE_FOLDER_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} new files to the library.
        /// </summary>
        public static string ENGINE_ADDED_N_NEW_FILES_MESSAGE {
            get {
                return ResourceManager.GetString("ENGINE_ADDED_N_NEW_FILES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the drive service to refresh the library files.
        /// </summary>
        public static string ENGINE_CONNECTING_DRIVE_SERVICE_MESSAGE {
            get {
                return ResourceManager.GetString("ENGINE_CONNECTING_DRIVE_SERVICE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} files through the drive engine.
        /// </summary>
        public static string ENGINE_FOUND_N_FILES_MESSAGE {
            get {
                return ResourceManager.GetString("ENGINE_FOUND_N_FILES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} files from the library that are no longer availabled.
        /// </summary>
        public static string ENGINE_REMOVED_N_FILES_MESSAGE {
            get {
                return ResourceManager.GetString("ENGINE_REMOVED_N_FILES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME_MAIN_TITLE {
            get {
                return ResourceManager.GetString("HOME_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add some libraries through the settings tab below.
        /// </summary>
        public static string HOME_NO_LIBRARY_WARNING_MESSAGE {
            get {
                return ResourceManager.GetString("HOME_NO_LIBRARY_WARNING_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any library defined yet.
        /// </summary>
        public static string HOME_NO_LIBRARY_WARNING_TITLE {
            get {
                return ResourceManager.GetString("HOME_NO_LIBRARY_WARNING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Going Reading.
        /// </summary>
        public static string HOME_ON_GOING_READING_SECTION_TITLE {
            get {
                return ResourceManager.GetString("HOME_ON_GOING_READING_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added.
        /// </summary>
        public static string HOME_RECENTLY_ADDED_SECTION_TITLE {
            get {
                return ResourceManager.GetString("HOME_RECENTLY_ADDED_SECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove the {0} library.
        /// </summary>
        public static string SETTINGS_DRIVE_REMOVE_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("SETTINGS_DRIVE_REMOVE_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to clear your local cache.
        /// </summary>
        public static string SETTINGS_LOCAL_CACHE_CLEAR_COMMAND {
            get {
                return ResourceManager.GetString("SETTINGS_LOCAL_CACHE_CLEAR_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear your local cache ?.
        /// </summary>
        public static string SETTINGS_LOCAL_CACHE_CLEAR_CONFIRMATION {
            get {
                return ResourceManager.GetString("SETTINGS_LOCAL_CACHE_CLEAR_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL CACHE.
        /// </summary>
        public static string SETTINGS_LOCAL_CACHE_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_LOCAL_CACHE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to megas.
        /// </summary>
        public static string SETTINGS_LOCAL_CACHE_UNITS {
            get {
                return ResourceManager.GetString("SETTINGS_LOCAL_CACHE_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a new Local Drive library.
        /// </summary>
        public static string SETTINGS_LOCAL_DRIVE_ADD_COMMAND {
            get {
                return ResourceManager.GetString("SETTINGS_LOCAL_DRIVE_ADD_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL DRIVE LIBRARIES.
        /// </summary>
        public static string SETTINGS_LOCAL_DRIVE_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_LOCAL_DRIVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS_MAIN_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a new One Drive library.
        /// </summary>
        public static string SETTINGS_ONE_DRIVE_ADD_COMMAND {
            get {
                return ResourceManager.GetString("SETTINGS_ONE_DRIVE_ADD_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE DRIVE LIBRARIES.
        /// </summary>
        public static string SETTINGS_ONE_DRIVE_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_ONE_DRIVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Readed.
        /// </summary>
        public static string SPLASH_DETAILS_READED_LABEL {
            get {
                return ResourceManager.GetString("SPLASH_DETAILS_READED_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously Read.
        /// </summary>
        public static string SPLASH_DETAILS_READING_LABEL {
            get {
                return ResourceManager.GetString("SPLASH_DETAILS_READING_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Editions From this Collection.
        /// </summary>
        public static string SPLASH_EDITIONS_TITLE {
            get {
                return ResourceManager.GetString("SPLASH_EDITIONS_TITLE", resourceCulture);
            }
        }
    }
}
